CREATE DATABASE desafio;
USE desafio;
CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50)

) 
ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO user ( name) VALUES ('Igor Cavalcante');



